<?php

function webform_signup_node_load($nodes, $types){
  if(is_object($nodes[5])){
    drupal_add_js(drupal_get_path( 'module', 'webform_signup') .'/js/webform_sign.js' );
    drupal_add_js(drupal_get_path( 'module', 'webform_signup') .'/js/jquery.autocomplete.js' );
  }
}
function webform_signup_menu() {

    $items=array();
	$items['checkschool']=array(
                                'page callback'=>'checkschoolName',
                                'access callback' => TRUE,
                                );
	$items['popup']=array(
                                'page callback'=>'popupPolicy',
                                'access callback' => TRUE,
                                );
	return $items;

}

function checkschoolName() {
        if ( ! civicrm_initialize( ) ) {
            return;
        }
        require_once 'CRM/Utils/Request.php';
        $sname = $_REQUEST['sname'];
        $sname = str_replace("_", " ", $sname);

        $checkid = webform_member($sname);
        if($checkid)
            echo 1;
        else
            echo 0;
}

function popupPolicy() {
    $nid  = 7;
    $node = node_load($nid);
    $node = $node->body[$node->language][0]['value'];
    print $node;
}

/* function webform_university(){ */
/*     if ( ! civicrm_initialize( ) ) { */
/*         return; */
/*     } */

/*     $params = array( */
/*                     'contact_type' => 'Organization', */
/*                     'contact_sub_type' => 'Higher_Education_Institution', */
/*                     'sort' => 'organization_name', */
/*                     'rowCount' => NULL, */
/*                     'version' => 3, */
/*                     ); */

/*     require_once 'api/api.php'; */
/*     $result = civicrm_api( 'contact','get',$params ); */

/*     return $result; */
/* } */

function webform_member($school) {
    if ( ! civicrm_initialize( ) ) {
        return;
    }
    $params = array( 
                    'contact_type' => 'Organization',
                    'contact_sub_type' => 'School',
                    'organization_name' => $school,
                    'version' => 3,
                     );

    require_once 'api/api.php';
    $result = civicrm_api( 'contact','get',$params );
    $chkmember = $result['id'];

    $member = CRM_Core_DAO::getFieldValue( 'CRM_Member_DAO_Membership', $chkmember, 'contact_id', 'contact_id' );

    return $member;
}

/* function webform_signup_civicrm_customFieldOptions($fieldID, &$options, $detailedFormat = false ) { */
/*     if($fieldID == 20){ */
/*         $result = webform_university(); */
/*         if (array_key_exists( 'values', $result ) && !empty($result['values']) ) { */
/*             foreach( $result['values'] as $valKey => $valValues ) { */
/*                 $options[$valValues['organization_name']] = $valValues['organization_name']; */
/*             } */
/*         } */
/*     } */
/* } */

?>
