<?php
function redirect_password_reset_form_alter(&$form, &$form_state, $form_id) {
	if($form_id == 'user_profile_form') {
		$form['#submit'][] = 'redirect_password_reset_profile_form_submit';
	}
}

function redirect_password_reset_profile_form_submit($form, &$form_state) {
	// Redirect back to CiviCRM if they are resetting their password.
	if(isset($_GET['pass-reset-token'])) {
		$form_state['redirect'] = 'civicrm';
	}
}
?>