<?php

function school_count_block_info() {
	$blocks['count'] = array(
		'info' => t('School count'),
	);
	return $blocks;
}

function school_count_block_view($delta = '') {
        switch ($delta){
                case 'count':
			$block['subject'] = 'School count';
			$block['content'] = school_count_get_text();
			return $block;
	}
}

function school_count_get_text(){
	civicrm_initialize();
	$query = 'SELECT count(*) AS count from civicrm_membership AS cm JOIN civicrm_membership_status AS cms ON cm.status_id=cms.id WHERE is_current_member=1;'; 
	$result=CRM_Core_DAO::executeQuery( $query, $params );
	$result->fetch();
	$count=(string)$result->count;
	return "<span class='integer'>{$count[0]}</span><span class='integer'>{$count[1]}</span><span class='integer'>{$count[2]}</span><div class='count-text'>Schools signed up</div>";
}

