<?php
function alumni_tokens_civicrm_tokens( &$tokens ) {
	$tokens['contact']['contact.alumni_school_for_text'] = "Alumni's short school name (for SMS)' ";
}

function alumni_tokens_civicrm_tokenValues( &$values, &$contactIDs ) {
	//foreach contact

	foreach($contactIDs as $id){
	//find out if they have an employer that is a school and if that is ark
	
	$sql="
	SELECT
		short_name_for_sms_79
	FROM
		civicrm_contact AS alumni
	JOIN
		civicrm_value_contact_reference_9 AS alumni_cd ON alumni.id=alumni_cd.entity_id
	JOIN
		civicrm_value_school_1 AS school_cd ON school_cd.entity_id=contact_reference_21
	WHERE
		alumni.id=%1
	";
	$params[1]=array($id, 'String');
	$result = CRM_Core_DAO::executeQuery( $sql, $params);
	if(!$result->fetch()){
		return;
	}
	//write a school name token
	$values[$id]['contact.alumni_school_for_text'] = $result->short_name_for_sms_79;
	}
}
