<?php
function alumni_tokens_civicrm_tokens( &$tokens ) {
	$tokens['contact']['contact.alumni_school_name_for_text'] = "Alumni's school's shortened name";
	$tokens['contact']['contact.alumni_school_addressee'] = "Alumni's school's addressee";
	$tokens['contact']['contact.alumni_school_programme_officer'] = "Alumni's school's programme officer";
}

function alumni_tokens_civicrm_tokenValues( &$values, &$contactIDs ) {
	//foreach contact

	foreach($contactIDs as $id){
		//find out if they have an employer that is a school and if that is ark
		
		$sql="
		SELECT
			school.addressee_display,
			short_name_for_sms_79,
			assigned_programme_officer_31
		FROM
			civicrm_contact AS alumni
		JOIN
			civicrm_value_contact_reference_9 AS alumni_cd ON alumni.id=alumni_cd.entity_id
		JOIN
			civicrm_contact AS school ON school.id=contact_reference_21
		JOIN
			civicrm_value_school_1 AS school_cd ON school_cd.entity_id=contact_reference_21
		WHERE
			alumni.id=%1
		";
		$params[1]=array($id, 'String');
		$result = CRM_Core_DAO::executeQuery( $sql, $params);
		if(!$result->fetch()){
			return;
		}
		//	write a school name token
		$values[$id]['contact.alumni_school_name_for_text'] = $result->short_name_for_sms_79;
		$values[$id]['contact.alumni_school_addressee'] = $result->addressee_display;
		$values[$id]['contact.alumni_school_programme_officer'] = $result->assigned_programme_officer_31;
	}
}
