<?php
/*
 * @file
 * Clientside validation install file
 */

/**
 * Implements hook_install().
 */
function clientside_validation_enable() {
  //support for module like e.g. select_or_other
  db_update('system')
    ->fields(array(
      'weight' => 5,
    ))
    ->condition('type', 'module')
    ->condition('name', 'clientside_validation')
    ->execute();
}

/**
 * Clientside validation was split up into form validation, webform validation and fapi validation.
 * This update enables the form and webform clientside validation module. It does not enable the
 * fapi clientside validation module, because it's a new feature since this release.
 */
function clientside_validation_update_7100() {
  module_enable(array('clientside_validation_form', 'clientside_validation_webform'));
}
