<?php
function fffb_block_info() {
	$blocks['authenticate'] = array(
		'info' => t('Sign up using Facebook'),
	);
	return $blocks;
}

function fffb_block_view($delta = '') {
	switch ($delta){
		case 'authenticate':
			$block['subject'] = 'Sign up using Facebook';
			$block['content'] = '<div id="fb-root"></div><div class="fb-login-button" scope="email, user_education_history, user_work_history">Login with Facebook</div>';
			break;
	}
	return $block;
}



