<?php
function fffb_theme() {
  return array(
    'facebook_block' => array('template' => 'fffb-facebook-block')
  );
}

function fffb_block_info() {
	$blocks['authenticate'] = array(
		'info' => t('Sign up using Facebook'),
	);
	return $blocks;
}

function fffb_block_view($delta = '') {
	switch ($delta){
		case 'authenticate':
			$block['subject'] = 'Sign up using Facebook';
			$block['content'] = theme('facebook_block'); 
			break;
	}
	return $block;
}



