<?php

function teachersrules_civicrm_aclWhereClause( $type, &$tables, &$whereTables, &$contactID, &$where ) {
    

    if(arg(0)=="civicrm" && arg(1)=="report" && arg(2)=="instance" && arg(3)==38){


        require_once 'api/api.php';
        
        $params = array( 
                        'version' => 3,
                        'contact_id_a' => $contactID,
                        'relationship_type_id' => 4,
                         );
        $result = civicrm_api( 'relationship','get',$params );

        $relid = $result['id'];
        $schoolid = $result['values'][$relid]['contact_id_b'];

        
        $sql = "SELECT entity_id FROM civicrm_value_contact_reference_9 WHERE contact_reference_21= $schoolid ";

        $dao = CRM_Core_DAO::executeQuery( $sql );
        $studentid = array();
        $i =0;
        while($dao->fetch()){
            $studentid[$i] = $dao->entity_id;
            $i++;
        }

        if ( ! empty( $studentid ) ) {
            $where .= ' AND contact_a.id IN(' . implode( ' , ', $studentid ) . ')';
        }

    }


  }

