<?php
function mobile_number_clean_civicrm_post( $op, $objectName, $objectId, &$objectRef ){
	
	if($objectName == "Individual") {
		
		$param = array(
			"version" => 3,
			"contact_id" => $objectId,
		);
		$result = civicrm_api("Phone", "Get", $param);

		foreach($result["values"] as $value) {
			
			// If there is any whitespace in the number then remove it.
			if (strpos($value["phone"], ' ') !== false) {
				$value["phone"] = str_replace(' ', '', $value["phone"]);
			}
			
			// If the mobile number is 10 digits long and begins with a 7,
			// add a leading 0.
			if (
				strlen($value["phone"]) == 10 &&
				substr($value["phone"], 0, 1) == "7"
			) {
				$value["phone"] = "0" . $value["phone"];
			}
			
			// If this number now looks like a mobile, then save it as mobile number,
			// otherwise if the number doesn't look like a mobile, and is currently
			// saved as a mobile, then move it to being a landline.
			if(
				substr($value["phone"], 0, 2) == "07" &&
				strlen($value["phone"]) == 11
			) {
			
				$updateParam = array(
					"version" => 3,
					"id" => $value["id"],
					"phone" => $value["phone"],
					"phone_type_id" => "2",
				);
					
				civicrm_api("Phone", "update", $updateParam);
			
			} else if($value["phone_type_id"] == "2") {
				
				$updateParam = array(
					"version" => 3,
					"id" => $value["id"],
					"phone_type_id" => "1",
				);
					
				civicrm_api("Phone", "update", $updateParam);
				
			}
			
		}

	}

}
