<?php

function ark_surveymonkey_redirect_menu() {
	$items['arksmr'] = array(
		'title' => 'Ark survey monkey redirect',
		'page callback' => 'ark_surveymonkey_redirect_redirect',
		'access arguments' => array('access content'), 
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function ark_surveymonkey_redirect_redirect(){
	$sid=$_GET['sid'];
	drupal_goto("https://www.surveymonkey.com/s/futurefirstarksignup?c={$sid}");
}
