<?php

//Use the druapal add js hook to add JS to the page to set the value to 1st of Jan and then hide the day and year

//check to see if we are on the alumni webform
function alumni_webform_node_view($node){
	//The webform ID is 14
	if ($node->nid==14 or $node->nid==17){
		drupal_add_js(drupal_get_path('module', 'alumni_webform').'/js/alumni_webform_hide_month_day_fields.js');
	} 
	if ($node->nid==5 or $node->nid==8){
		drupal_add_js(drupal_get_path('module', 'alumni_webform').'/js/alumni_webform_hide_leaving_date.js');
	}	
	//If we are on the Student or Student ark form we want to collect the year but hide the entire date picker so that it can't be changed.
}
?>
