<?php
// a block for displaying the school name
function student_form_block_info() {
	$blocks['info'] = array(
		'info' => t('School name'),
	);
	return $blocks;
}

function student_form_block_view($delta = '') {
	$block['subject'] = 'School name';
	$school = student_form_get_school_from_url();
	$block['content'] = $school['display_name'];
	return $block;
}

function student_form_get_school_from_url(){
	civicrm_initialize();
	$contact_ref = arg(2);
	
	//query to see if the reference exists
	$sql = 'SELECT entity_id FROM civicrm_value_school_1 WHERE short_name_26=%1';
	$params[1] = array($contact_ref, 'String');
	$result = CRM_Core_DAO::executeQuery( $sql, $params);
	if(!$result->fetch()){
		return;
	};
	$contact_id = $result->entity_id;
	$params = array('version'=>3, 'id'=>$contact_id);
	$school = civicrm_api('Contact', 'getsingle', $params);
	return $school;

}

function student_from_get_membership($contact_id){
	$membership_params = array (
		'version' =>'3',
		'contact_id' => $contact_id
	);
	$membership_result=civicrm_api("membership", "get", $membership_params);
	if($membership_result['count']==0){
		return FALSE;
	}else{
		return $membership_result;
	}
}

function student_form_webform_submission_presave($node, &$submission){
	$school = civicrm_api('Contact', 'getsingle', $params);
	$submission->data[16]['value'][0]=$school['id'];
}	

function student_form_node_load($nodes, $types){
	if(is_object($nodes[8]) OR is_object($nodes[5])){
	  
		drupal_add_js(drupal_get_path( 'module', 'student_form') .'/webform-hide-fields.js' ); 
		
		$school = student_form_get_school_from_url();
                if(!arg(2) && $_SESSION['school_id']){
                        drupal_goto('signup/'.$_SESSION['school_id']);
                }

		$membership = student_from_get_membership($school['id']);
		if(is_array($membership)){
		// 'is a member';
		}else{
			drupal_goto('');
		}
	}
}
